[project]
name = "vonsneg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "pre-commit>=4.2.0",
    "ruff>=0.11.3",
]
[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
line-length = 120